#%RAML 1.0 NamedExample
value: |
  [
    {
      "id": 1,
      "username": "testingham5000",
      "firstName": "Ted",
      "lastName": "Testingham",
      "phone": "1231231234",
      "email": "testingham5000@ephasus.com",
      "address1": "101 Test Way",
      "address2": "Apt 42",
      "city": "Denver",
      "state": "CO",
      "zip": "80210"
    },
    {
      "id": 2,
      "username": "testerson101",
      "firstName": "Tori",
      "lastName": "Testerson",
      "phone": "1231231234",
      "email": "testerson101@ephasus.com",
      "address1": "567 Test Blvd",
      "address2": "Apt 1",
      "city": "Denver",
      "state": "CO",
      "zip": "80210"
    }
  ]