#%RAML 1.0 NamedExample
value: |
  {
    "customerId": 12345566,
    "orderDate": "2015-07-04T21:00:00",
    "totalPrice": 100.00,
    "orderSource": "shopify",
    "orderSourceId": "123asdfb123",
    "orderItems": [
      {
        "productId": 123456,
        "price": 10.00,
        "quantity": 2
      },
      {
        "productId": 234567,
        "price": 80.00,
        "quantity": 1
      }
    ]
  }