#%RAML 1.0 NamedExample
value: |
  [
    {
      "id": 987654321,
      "customerId": 12345566,
      "orderDate": "2015-07-04T21:00:00",
      "totalPrice": 100.00,
      "orderItems": [
        {
          "id": 345876345,
          "orderId": 987654321,
          "productId": 123456,
          "price": 10.00,
          "quantity": 2
        },
        {
          "id": 345876346,
          "orderId": 987654321,
          "productId": 234567,
          "price": 80.00,
          "quantity": 1
        }
      ]
    },
    {
      "id": 987654322,
      "customerId": 12345566,
      "orderDate": "2016-07-04T21:00:00",
      "totalPrice": 200.00,
      "orderItems": [
        {
          "id": 345876347,
          "orderId": 987654322,
          "productId": 123456,
          "price": 50.00,
          "quantity": 2
        },
        {
          "id": 345876348,
          "orderId": 987654322,
          "productId": 234567,
          "price": 100.00,
          "quantity": 1
        }
      ]
    }
  ]