#%RAML 1.0
title: product-api-walkthrough
baseUri: http://localhost:8081/product
version: 1.0
types: 
  product:
    properties: 
      id: number
      name?: string
      price?: number
      sku?: string
      inventory?: number
      shopifyProductId?: number

/products:
  get:
    queryParameters: 
      sku?: string
      inShopify?:
        type: boolean
        description: If false the product has not been copied to Shopify
    responses: 
      200:
        description: Return a collection of products
        body: 
          application/json:
            example: |
                [
                  {
                    "id": 4,
                    "name": "Walkie Talkie",
                    "price": 50.00,
                    "sku": "efg456",
                    "inventory": 15,
                    "shopifyProductId": 748276613218
                  },
                  {
                    "id": 5,
                    "name": "Television",
                    "price": 100.50,
                    "sku": "abc56",
                    "inventory": 1,
                    "shopifyProductId": 848276613218
                  }
                ]
            
  /{productId}:
      patch:
        description: Update product
        body: 
          application/json:
            type: product
            example: |
              {
                "id": 4,
                "shopifyProductId": 748276613218
              }
        responses: 
          200:
            body: 
              application/json:
                example: |
                  {
                    "message": "Product was updated"
                  }
                  